In [10]:
import pickle

import pandas as pd

df = pd.read_csv('hand_landmarks_with_class.csv')

In [11]:
df.head()

x0   y0            z0        x1        y1        z1        x2  \
0  0.653857  1.0 -4.300987e-07  0.225498  0.827666 -0.024403  0.000000   
1  0.684381  1.0 -4.096430e-07  0.281581  0.834015 -0.023313  0.042803   
2  0.689282  1.0 -3.826779e-07  0.309815  0.813003 -0.021545  0.093782   
3  0.682848  1.0 -5.706927e-07  0.285623  0.797552 -0.030813  0.086013   
4  0.693486  1.0 -4.964141e-07  0.312429  0.808850 -0.029908  0.100978   

         y2        z2        x3  ...       x18       y18       z18       x19  \
0  0.511278 -0.032231  0.007469  ...  0.980599  0.316391 -0.033982  0.918933   
1  0.502138 -0.031375  0.016980  ...  0.975959  0.324422 -0.040324  0.915524   
2  0.490741 -0.029024  0.056653  ...  0.991433  0.228252 -0.028059  0.929653   
3  0.474516 -0.042250  0.054851  ...  0.983159  0.227716 -0.034430  0.902608   
4  0.476277 -0.039655  0.056138  ...  0.986793  0.240662 -0.030113  0.924047   

        y19       z19       x20       y20       z20  Class  
0  0.492250 -0.033129  0.875054  0.645383 -0.025987      A  
1  0.508190 -0.039211  0.873538  0.656957 -0.032229      A  
2  0.421055 -0.016451  0.936364  0.457611 -0.005049      A  
3  0.421035 -0.019471  0.924137  0.447328 -0.007248      A  
4  0.437124 -0.016046  0.940514  0.455040 -0.003580      A  

[5 rows x 64 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 64 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   x0      280 non-null    float64
 1   y0      280 non-null    float64
 2   z0      280 non-null    float64
 3   x1      280 non-null    float64
 4   y1      280 non-null    float64
 5   z1      280 non-null    float64
 6   x2      280 non-null    float64
 7   y2      280 non-null    float64
 8   z2      280 non-null    float64
 9   x3      280 non-null    float64
 10  y3      280 non-null    float64
 11  z3      280 non-null    float64
 12  x4      280 non-null    float64
 13  y4      280 non-null    float64
 14  z4      280 non-null    float64
 15  x5      280 non-null    float64
 16  y5      280 non-null    float64
 17  z5      280 non-null    float64
 18  x6      280 non-null    float64
 19  y6      280 non-null    float64
 20  z6      280 non-null    float64
 21  x7      280 non-null    float64
 22  y7

In [20]:
label_col = "Class"
SEED = 42

In [21]:
from sklearn.preprocessing import LabelEncoder
X, y = df.drop(label_col, axis=1), df[label_col].copy()
label = LabelEncoder()
X_processed = X
y_processed = label.fit_transform(y)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_processed, y_processed,
                                                    test_size=0.2, random_state=SEED,
                                                    stratify=y_processed)

In [23]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((224, 63), (224,), (56, 63), (56,))

In [22]:
X_train[:2], y_train[:2], label.classes_

(           x0   y0            z0        x1        y1        z1        x2  \
 119  0.740638  1.0 -3.327845e-08  0.455437  0.934224 -0.018336  0.191519   
 148  1.000000  1.0 -4.324605e-07  0.945075  0.626736  0.007530  0.756512   
 
            y2        z2        x3  ...       z17       x18       y18  \
 119  0.801391 -0.032366  0.000000  ... -0.022927  0.866649  0.342613   
 148  0.372849 -0.001085  0.534918  ... -0.068433  0.384722  0.678100   
 
           z18       x19       y19       z19       x20       y20       z20  
 119 -0.033404  0.936372  0.236874 -0.039351  1.000000  0.143667 -0.043225  
 148 -0.079664  0.359233  0.754757 -0.070970  0.418461  0.815554 -0.062491  
 
 [2 rows x 63 columns],
 array([5, 7]),
 array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N',
        'O'], dtype=object))

In [54]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [57]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
y_preds = neigh.predict(X_test)
print(accuracy_score(y_test, y_preds))
print(confusion_matrix(y_test, y_preds))


1.0
[[4 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 4 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 4 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 4 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 4]]


In [61]:
import pickle
pickle.dump((neigh, label), open('neigh-model.pkl', 'wb'))

In [55]:
import tensorflow as tf
from tensorflow.keras import layers, Input
from tensorflow.keras.models import Sequential


class RelativePositionLayer(layers.Layer):
    def call(self, inputs):
        # Reshape from (63,) to (21, 3)
        coords = tf.reshape(inputs, (-1, 21, 3))
        diffs = tf.expand_dims(coords, 2) - tf.expand_dims(coords, 1)
        distances = tf.norm(diffs, axis=-1)  # Euclidean distances
        return distances  # shape: (21, 21)

In [44]:
num_classes = len(label.classes_)
model = Sequential([
    Input((63,)),
    RelativePositionLayer(),
    layers.Flatten(),                      # flatten to (441,)
    layers.Dense(128, activation='relu'),  # fully connected layer
    layers.Dense(64, activation='relu'),   # another layer
    layers.Dense(num_classes, activation='softmax')  # output layer
])

In [51]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
              metrics=['accuracy'])

In [49]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ relative_position_layer_8       │ (None, 21, 21)         │             0 │
│ (RelativePositionLayer)         │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_8 (Flatten)             │ (None, 441)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 128)            │        56,576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 14)             │           910 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 65,742 (256.80 KB)

 Trainable params: 65,742 (256.80 KB)

 Non-trainable params: 0 (0.00 B)

In [52]:
X_train.shape

(224, 63)

In [53]:
epochs = 10

history = model.fit(
    x=X_train,
    y=y_train,
    validation_data=0.2,
    epochs=epochs
)


Epoch 1/10
1/7 ━━━━━━━━━━━━━━━━━━━━ 4s 771ms/step - accuracy: 0.2188 - loss: 2.3331

ValueError: Unrecognized data type: x=0.2 (of type <class 'float'>)