In [73]:
import pickle
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

In [74]:
df = pd.read_csv('hand_landmarks_with_class.csv')
df.head()

x0   y0            z0        x1        y1        z1        x2  \
0  0.653857  1.0 -4.300987e-07  0.225498  0.827666 -0.024403  0.000000   
1  0.684381  1.0 -4.096430e-07  0.281581  0.834015 -0.023313  0.042803   
2  0.644851  1.0 -4.480389e-07  0.223254  0.835974 -0.025317  0.000000   
3  0.650092  1.0 -4.558451e-07  0.228792  0.835841 -0.027375  0.000000   
4  0.650874  1.0 -7.040561e-07  0.240213  0.833934 -0.030194  0.023338   

         y2        z2        x3  ...       x18       y18       z18       x19  \
0  0.511278 -0.032231  0.007469  ...  0.980599  0.316391 -0.033982  0.918933   
1  0.502138 -0.031375  0.016980  ...  0.975959  0.324422 -0.040324  0.915524   
2  0.508345 -0.034005  0.004898  ...  0.983472  0.324955 -0.039386  0.915539   
3  0.513270 -0.037301  0.002446  ...  0.984744  0.314274 -0.042836  0.915201   
4  0.505647 -0.040968  0.018000  ...  0.947008  0.289619 -0.055235  0.876328   

        y19       z19       x20       y20       z20  Class  
0  0.492250 -0.033129  0.875054  0.645383 -0.025987      A  
1  0.508190 -0.039211  0.873538  0.656957 -0.032229      A  
2  0.504322 -0.037639  0.867808  0.650879 -0.030341      A  
3  0.491869 -0.041915  0.865774  0.641248 -0.034912      A  
4  0.474258 -0.052679  0.836052  0.625443 -0.042452      A  

[5 rows x 64 columns]

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 64 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   x0      240 non-null    float64
 1   y0      240 non-null    float64
 2   z0      240 non-null    float64
 3   x1      240 non-null    float64
 4   y1      240 non-null    float64
 5   z1      240 non-null    float64
 6   x2      240 non-null    float64
 7   y2      240 non-null    float64
 8   z2      240 non-null    float64
 9   x3      240 non-null    float64
 10  y3      240 non-null    float64
 11  z3      240 non-null    float64
 12  x4      240 non-null    float64
 13  y4      240 non-null    float64
 14  z4      240 non-null    float64
 15  x5      240 non-null    float64
 16  y5      240 non-null    float64
 17  z5      240 non-null    float64
 18  x6      240 non-null    float64
 19  y6      240 non-null    float64
 20  z6      240 non-null    float64
 21  x7      240 non-null    float64
 22  y7

In [76]:
label_col = "Class"
SEED = 42

In [77]:
X, y = df.drop(label_col, axis=1).to_numpy(), df[label_col].copy().to_numpy()
label = LabelEncoder()
X_processed = X
y_processed = label.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X_processed, y_processed,
                                                    test_size=0.2, random_state=SEED,
                                                    stratify=y_processed)

In [78]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((192, 63), (192,), (48, 63), (48,))

In [79]:
X_train[:2], y_train[:2], label.classes_

(array([[ 6.90522277e-01,  1.00000000e+00, -5.31034232e-07,
          2.85156251e-01,  8.46086694e-01, -2.14595199e-02,
          4.81057121e-02,  5.12002016e-01, -2.79994812e-02,
          2.47165803e-02,  2.33435717e-01, -3.46642025e-02,
          0.00000000e+00,  0.00000000e+00, -3.78655940e-02,
          2.76648775e-01,  2.88839870e-01, -1.87558506e-03,
          2.63496463e-01,  1.55123123e-01, -3.05577070e-02,
          3.12412959e-01,  3.91060710e-01, -4.86416407e-02,
          3.45309987e-01,  5.99872150e-01, -5.54788373e-02,
          5.34778060e-01,  2.87955041e-01, -1.77200360e-03,
          5.02347511e-01,  1.72985293e-01, -3.31234224e-02,
          5.25643059e-01,  4.57026163e-01, -4.43290137e-02,
          5.35617639e-01,  6.77419409e-01, -4.39919643e-02,
          7.73386201e-01,  3.16372865e-01, -7.09647499e-03,
          7.42554390e-01,  2.08500187e-01, -3.85604687e-02,
          7.24188953e-01,  4.87581163e-01, -3.63708064e-02,
          7.04524452e-01,  6.94681657e-0

In [80]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [81]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
y_preds = neigh.predict(X_test)
print(accuracy_score(y_test, y_preds))
print(confusion_matrix(y_test, y_preds))

1.0
[[2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0

In [82]:
pickle.dump((neigh, label), open('neigh-model.pkl', 'wb'))